resource_group_name   = "RG-AZFUNCCI-DEV-01"
app_service_plan_name = "ASP-WESTEUROPE-AZFUNCCI-DEV-01"
api_service_plan_name = "ASP-WESTEUROPE-API-DEV-01"
storage_account_name  = "saazfunccidev"
function_app_name     = "fnapp-neolutin-dev-01"
api_name              = "wa-api-neolutin-dev-01"
dataapi_url           = "https://wa-api-neolutin-dev-01.azurewebsites.net"