resource_group_name   = "rg-azfuncci-dev-01"
location              = "west europe"
app_service_plan_name = "asp-westeurope-azfuncci-dev-01"
api_service_plan_name = "asp-westeurope-api-dev-01"
storage_account_name  = "saazfunccidev"
function_app_name     = "fnapp-neolutin-dev-01"
api_name              = "wa-api-neolutin-dev-01"
dataapi_url           = "https://wa-api-neolutin-dev-01.azurewebsites.net"
