name: azFuncCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraformPack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 1.0

    - name: Init
      run: cd terraform && terraform init

    - name: Plan
      run: cd terraform && terraform plan -input=false -out='out.tfplan'
      
    - name: Upload an Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: terraform
        path: terraform/out.tfplan
        
  dataApiBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: cd DataApi && dotnet restore
      
    - name: Build
      run: cd DataApi && dotnet build --no-restore  -c Release
    - name: Test
      run: cd DataApi && dotnet test --no-build --verbosity normal -c Release
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: DataApi
        path: DataApi/bin/Release

  functionBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: FunctionCompute
    - name: Build
      run: dotnet build --no-restore  -c Release
      working-directory: FunctionCompute
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
      working-directory: FunctionCompute
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: FunctionCompute
        path: FunctionCompute/bin/Release

  deployInfra:
    environment:
      name: funcApiDev
    needs: terraformPack
    runs-on: ubuntu-latest
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 1.0
    - name: Download terraform plan
      uses: actions/download-artifact@v2.0.10
      with:
        name: terraform
    - name: Apply
      run: terraform apply terraform/out.tfplan

  deployFunction:
    needs: [functionBuild, deployInfra]
    runs-on: ubuntu-latest
    steps:
    - name: Todo
      run: echo todo
