name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: cd DataApi && dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: cd DataApi && dotnet test --no-build --verbosity normal
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: monolith
        path: DataApi/bin/Release
  
